version: "3"

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - ./front-end:/sample-projects/front-end
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true